// Auth
export const AUTH_SET_FIREBASE_ID_TOKEN = 'AUTH_SET_FIREBASE_ID_TOKEN';
export const AUTH_SET_BLOOPER_TOKEN = 'AUTH_SET_BLOOPER_TOKEN';
export const AUTH_SET_USER = 'AUTH_SET_USER';

// Search
export const SEARCH_SET_QUERY = 'SEARCH_SET_QUERY';
export const SEARCH_SET_RESULTS = 'SEARCH_SET_RESULTS';
